@startuml
'https://plantuml.com/deployment-diagram

skinparam nodeBackgroundColor LightSkyBlue
skinparam nodeBorderColor DeepSkyBlue
skinparam artifactBackgroundColor LightGreen
skinparam artifactBorderColor Green
skinparam componentBackgroundColor LightYellow
skinparam packageBackgroundColor LightGray
skinparam packageBorderColor DarkGray
skinparam stereotypeCBackgroundColor YellowGreen
skinparam shadowing true
skinparam roundcorner 10

title Deployment Diagram - Infrastructure View

header
  <font color=blue>UML Generator</font>
  Infrastructure Topology from Jaeger Traces
endheader

package "Backend Zone" #LightGreen {
  node "Node-8353" {
    artifact "checkoutservice" <<API>>
  }
  node "currencyservice-6d559b9456-xmf5z" {
    artifact "currencyservice" <<API>>
  }
}


legend right
  |= Zone |= Services |
  | Backend Zone | 2 |
  
  **Stereotypes:**
  * <<Web>> - Frontend/UI Service
  * <<API>> - Backend Service
  * <<DB>> - Database Service
  * <<Cache>> - Caching Layer
endlegend

footer
  Generated: 2025-12-16 13:35:35 | Zones: 1 | Nodes: 2 | Services: 2
endfooter

@enduml